import './components/game.component'
import './components/selfdestruct.component'
import './components/pixelshader.component'
import './components/controls.component'
import './components/explosion.component'
import './components/shoot-controls.component'
import './components/entities/block-entity.component'
import './components/entities/target-entity.component'
import './components/entities/placeholder-entity.component'
import './components/score.component'
import './components/selectToPlace.component';
import './components/click-handler.component';
import './components/towerdefense.system';
import './components/bullet.component';
import './components/tower.component';
import './components/enemy.component';
import './components/spawner.component';
import './components/defense.component';
import './components/map.component';
import './components/title-screen.component'
import './components/neon-text.component'